### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by alevenberg**
Fix issue #11

### CODE REVIEW

**Comment by pnpnpn** [comment]
Thanks for creating the PR. The build is failing on python36: https://travis-ci.org/pnpnpn/dna2vec/jobs/642044658?utm_medium=notification&utm_source=github_status

**Comment by alevenberg** [comment]
It looks like it's getting the error  
RuntimeError: Python version >= 3.5 required 
if looks like only 3.4 is failing because some dependencies require 3.6

**Comment by pnpnpn** [comment]
You can remove 3.4 support. It's in tox.ini. Thanks!

**Comment by alevenberg** [comment]
Sounds good! All fixed up!

**Pull request merged**
